Adds all functions
JanekJaniak/TodoList pull request #4
Opened 2020-10-06 21:55 UTC by JanekJaniak

I did it, but without filter or map in remove function.

2020-10-07 06:46 UTC, zodybek approved these changes
no piknie

2020-10-07 06:46 UTC, zodybek commented on index.js
> +        listItem.innerHTML=items[index].value + '<button data-deleteButton>Delete</button>';
wydaje mi się, że to można lepiej zapisać, żeby nie przepisywać HTML-a do JS... ale nie mam teraz pomysłu jak ;-)

2020-10-07 18:47 UTC, jan-gajdowicz requested changes

2020-10-07 18:47 UTC, jan-gajdowicz commented on index.js
>  }
All this function should do is push an item into `items` array. 
It should take `newItem` as an argument. 
`newItem` should be an object with `id` and `value`

2020-10-07 18:47 UTC, jan-gajdowicz commented on index.js
>  }
All this function should do is filter `items` array

2020-10-07 18:47 UTC, jan-gajdowicz commented on index.js
> +    list.textContent='';
This would not work

2020-10-07 18:47 UTC, jan-gajdowicz commented on index.js
> +        listItem.innerHTML=items[index].value + '<button data-deleteButton>Delete</button>';
`items[index] === item`

2020-10-07 18:47 UTC, jan-gajdowicz commented on index.js
> +        listItem.innerHTML=items[index].value + '<button data-deleteButton>Delete</button>';
Please use `appendNode` method

2020-10-07 18:47 UTC, jan-gajdowicz commented on index.js
> +addButton.addEventListener('click', addItem);
Pass a `newItem` argument to `addItem` & call `renderItems`

2020-10-07 18:49 UTC, jan-gajdowicz commented
> no piknie

@zodybek Please try to avoid unrelated comments

2020-10-07 18:51 UTC, jan-gajdowicz commented
@JanekJaniak Please try to implement code review feedback
@zodybek Please try commenting in english and do not approve a PR that is not ready to be merged

2020-10-15 20:27 UTC, JanekJaniak commented
I did new render function. Don't know how and why I need to use filter method in remove function, so I stopped there.

2020-10-18 19:54 UTC, merged